version: '3.8'

services:
  # Laravel PHP
  backend-laravel-php:
    build:
      context: ./blog-system-be
    volumes:
      - ./blog-system-be:/var/www
    environment:
      DB_HOST: db
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USERNAME}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      APP_URL: ${APP_URL}
    command: sh -c "cp .env.example .env && composer install && php artisan key:generate && php artisan migrate && php-fpm"
    networks:
      - app-network
    depends_on:
      - db

  laravel-nginx:
    image: nginx:alpine
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./blog-system-be:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - backend-laravel-php

  frontend-nuxt:
    build:
      context: ./blog-system-fe
    volumes:
      - ./blog-system-fe:/app
      - /app/node_modules
    environment:
      APP_URL: ${NUXT_APP_URL}
      API_URL: ${NUXT_API_URL}
    ports:
      - "${NUXT_APP_PORT}:3000"
    command: sh -c "npm run dev"
    networks:
      - app-network
  
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data: