FROM node:20 AS builder

WORKDIR /app

COPY . .

RUN npm install
RUN NODE_ENV=production npm run generate

FROM node:20-alpine AS production

WORKDIR /usr/share/nginx/html

RUN npm install -g serve
COPY --from=builder /app/.output/public .

EXPOSE 3000
CMD ["serve", "-s", ".", "-l", "3000"]